# Tools - NumPy

This file was created solely for the purpose of practicing features of the NumPy library and doesn't serve any other specific purpose.

In [3]:
import numpy as np

In [4]:
np.zeros(11) # create an array containing only zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((5, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
my_array = np.zeros((4, 9))
my_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
my_array.shape # shape - list of axis lengths

(4, 9)

In [20]:
my_array.ndim # rank - number of axes (dimensions)

2

In [19]:
my_array.size # size, 4 * 9 = 36

36

In [25]:
dim_3_array = np.zeros((3, 2, 6)) # the 3-dimensional array
dim_3_array

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [27]:
type(dim_3_array)

numpy.ndarray

In [30]:
np.ones((2, 3)) # array full of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.full((2, 3), np.Inf) # array full of infinities

array([[inf, inf, inf],
       [inf, inf, inf]])

In [45]:
np.empty((2, 3)) # array with elements that are in memory at this point

array([[inf, inf, inf],
       [inf, inf, inf]])

In [44]:
np.empty((3, 3)) # same method but different "memory location"

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.69119330e-306, 6.23059386e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 5.33590898e-322]])

In [47]:
np.array(([1, 2, 3], [4, 5, 6])) # array initialization

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.arange(1, 10, 2) # create an array using similar method to the built-in python function range()

array([1, 3, 5, 7, 9])

It is not recommended to use floats - when dealing with floats, the exact number of elements in the array is not always predictable.

In [52]:
np.arange(0, 5/3, 1/3) # 

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])